const state={exercise:null,history:[],attempt:0};
const labels={NORMAL_CONDITION:"正常执行条件",FORWARD_POSTCONDITION:"关注方向后置条件",INVERSE_POSTCONDITION:"粉丝方向后置条件",FIRST_USER_MISSING:"id1 不存在",SECOND_USER_MISSING:"id2 不存在",SELF_FOLLOW:"自我关注",DUPLICATE_FOLLOW:"重复关注"};
const verdictLabels={READY_FOR_DETERMINISTIC_CHECK:"可进入确定性检查",NEEDS_REVISION:"需要修改",INCOMPLETE:"尚未完成",UNCERTAIN:"暂无法判断"};
const $=id=>document.getElementById(id);

function assemble(){let text=state.exercise.template;for(const key of state.exercise.placeholders){const input=document.querySelector(`[data-blank="${key}"]`);text=text.replace(`{{${key}}}`,input?.value.trim()||`{{${key}}}`)}$('submission').value=text}
function buildFields(){const box=$('blank-fields');box.innerHTML='';for(const key of state.exercise.placeholders){const row=document.createElement('div');row.className='field';row.innerHTML=`<label for="blank-${key}">${labels[key]||key}</label><input id="blank-${key}" data-blank="${key}" autocomplete="off" placeholder="填写 JML 表达式">`;row.querySelector('input').addEventListener('input',assemble);box.appendChild(row)}assemble()}
function literalPattern(text){return text.split(/(\s+)/).filter(Boolean).map(part=>/^\s+$/.test(part)?'\\s+':part.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('')}
function loadSample(content){const parts=state.exercise.template.split(/\{\{([A-Z0-9_]+)\}\}/g);let pattern=`^${literalPattern(parts[0])}`;state.exercise.placeholders.forEach((_,index)=>{pattern+=`([\\s\\S]*?)${literalPattern(parts[index*2+2])}`});const match=content.match(new RegExp(pattern));if(!match){$('feedback-content').textContent='该样例与当前模板不匹配。';$('feedback-content').classList.remove('hidden');return}state.exercise.placeholders.forEach((key,index)=>{document.querySelector(`[data-blank="${key}"]`).value=match[index+1].replace(/\n\s*@\s*/g,' ').trim()});assemble()}
function renderRequirement(text){$('requirement').textContent=text.replace(/^# .*\n+/,'').trim()}
function escapeHtml(value){const div=document.createElement('div');div.textContent=value;return div.innerHTML}
function renderChecks(checks){return `<div class="check-list">${checks.map(x=>`<div class="check ${x.severity==='error'?'error':''}"><strong>${escapeHtml(x.code)}</strong><br>${escapeHtml(x.message)}</div>`).join('')}</div>`}
function renderSemantic(result){if(!result)return '';const status=result.passed?'通过':'需要修改';const score=Number.isFinite(result.score)?`${result.score}/100`:'未评分';const diagnostics=Array.isArray(result.diagnostics)?result.diagnostics:[];const items=diagnostics.length?diagnostics.map(item=>`<div class="check error"><strong>${escapeHtml(item.category||'规格问题')}</strong><br><span>位置：${escapeHtml(labels[item.location]||item.location||'未定位')}</span><br><span>${escapeHtml(item.observation||'存在与参考规格不一致的情况。')}</span><br><span>${escapeHtml(item.guidance||'请回到需求，检查该义务。')}</span></div>`).join(''):'<div class="check"><strong>未发现已覆盖义务中的语义问题</strong><br>仍请自行检查未覆盖的边界情况。</div>';return `<section class="semantic-result"><h3>确定性规格评测：${status}（${score}）</h3><p>以下结论由服务器端规则判定；Agent 只负责解释，不决定得分。</p><div class="check-list">${items}</div></section>`}
function renderCoach(coach){if(!coach)return '';const issues=Array.isArray(coach.issues)?coach.issues:[];const correct=Array.isArray(coach.correct_parts)?coach.correct_parts:[];const issueCards=issues.length?issues.map(issue=>`<article class="coach-card issue"><div class="coach-card-heading"><span>${escapeHtml(labels[issue.location]||issue.location||'未定位')}</span><strong>${escapeHtml(issue.category||'需要注意')}</strong></div><p>${escapeHtml(issue.explanation||'请结合确定性评测结果检查此处。')}</p>${issue.counterexample?`<p class="coach-observation">${escapeHtml(issue.counterexample)}</p>`:''}</article>`).join(''):'<article class="coach-card"><strong>没有额外的 Agent 问题说明</strong><p>请以确定性规格评测结果为准。</p></article>';const correctCards=correct.length?`<div class="coach-correct"><strong>已确认的部分</strong><ul>${correct.map(item=>`<li>${escapeHtml(item)}</li>`).join('')}</ul></div>`:'';return `<section class="coach-result"><div class="coach-title"><div><span class="eyebrow">AGENT · EXPLAIN</span><h3>学习指导</h3></div><span class="coach-verdict">${escapeHtml(verdictLabels[coach.verdict]||'学习建议')}</span></div><article class="coach-card summary"><strong>总结</strong><p>${escapeHtml(coach.progress_summary||'请以确定性规格评测结果为准。')}</p></article>${correctCards}<div class="coach-issues"><h4>需要注意</h4>${issueCards}</div><article class="coach-card next-step"><strong>下一步</strong><p>${escapeHtml(coach.next_step||'根据评测结果修改后重新提交。')}</p></article></section>`}
function renderChain(name,result){const verdict=result?.verdict||'UNKNOWN';const diagnostics=Array.isArray(result?.diagnostics)?result.diagnostics:[];const score=Number.isFinite(result?.evidence?.score)?` · ${result.evidence.score}/100`:'';const success=verdict==='PASS'?'<p>已覆盖的语义义务全部满足。</p>':'';return `<article class="chain-card ${verdict==='PASS'?'pass':verdict==='FAIL'?'fail':'unknown'}"><div><strong>${escapeHtml(name)}</strong><span>${escapeHtml(verdict+score)}</span></div>${success}${diagnostics.slice(0,2).map(x=>`<p>${escapeHtml(x.category||x.code)}：${escapeHtml(x.observation||'')}</p>`).join('')}</article>`}
function showConsistencyCase(){const item=state.exercise.consistency_demo_cases.find(x=>x.id===$('consistency-case').value);if(!item)return;$('case-description').innerHTML=`<strong>${escapeHtml(item.label)}</strong><span>${escapeHtml(item.description)}</span>`;$('case-jml').textContent=item.jml_excerpt;$('case-java').textContent=item.java_excerpt;$('case-expected').textContent=`预期 ${item.expected}`;$('consistency-result').innerHTML='<div class="result-placeholder">代码已载入，点击“运行双检测”验证预期</div>'}
async function runConsistencyDemo(){const button=$('consistency-button');button.disabled=true;$('consistency-result').innerHTML='<p class="demo-running">正在运行 Requirement Judge 与 OpenJML ESC…</p>';try{const response=await fetch('/api/demo-consistency',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({case_id:$('consistency-case').value})});const data=await response.json();if(!response.ok)throw new Error(data.error||'双检测失败');const result=data.result;$('consistency-result').innerHTML=`<div class="chain-grid">${renderChain('C1 · 题意 → JML',result.nl_jml)}${renderChain('C2 · JML → Java',result.jml_java)}</div><div class="overall-result">综合结论：<strong>${escapeHtml(result.overall)}</strong></div>`}catch(error){$('consistency-result').innerHTML=`<div class="check error">${escapeHtml(error.message)}</div>`}finally{button.disabled=false}}
async function submit(){assemble();const submission=$('submission').value;const mode=$('mode').value;const button=$('submit-button');button.disabled=true;$('empty-feedback').classList.add('hidden');$('feedback-content').classList.add('hidden');$('checking').classList.remove('hidden');try{const response=await fetch('/api/review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({submission,mode,history:state.history})});const data=await response.json();if(!response.ok)throw new Error(data.error||'审查失败');state.attempt++;$('feedback-content').innerHTML=renderChecks(data.checks)+renderSemantic(data.semantic)+renderCoach(data.coach);$('feedback-content').classList.remove('hidden');state.history.push({submission,coach:data.coach,mode});const item=document.createElement('div');item.className='history-item';item.textContent=`第 ${state.attempt} 次提交 · ${mode} · 已保留用于下一轮反馈`; $('history').prepend(item)}catch(error){$('feedback-content').textContent=`暂时无法完成审查：${error.message}`;$('feedback-content').classList.remove('hidden')}finally{$('checking').classList.add('hidden');button.disabled=false}}
function reset(){document.querySelectorAll('[data-blank]').forEach(x=>x.value='');state.history=[];state.attempt=0;$('history').innerHTML='';$('feedback-content').classList.add('hidden');$('empty-feedback').classList.remove('hidden');assemble()}
async function init(){const response=await fetch('/api/exercise');state.exercise=await response.json();$('exercise-title').textContent=state.exercise.title;$('method-name').textContent=state.exercise.method;renderRequirement(state.exercise.requirement);$('mode').value=state.exercise.default_mode;buildFields();const select=$('sample-select');for(const sample of state.exercise.samples||[]){const option=document.createElement('option');option.value=sample.id;option.textContent=sample.label;select.appendChild(option)}select.addEventListener('change',()=>{const sample=state.exercise.samples.find(x=>x.id===select.value);if(sample)loadSample(sample.content)});const caseSelect=$('consistency-case');for(const item of state.exercise.consistency_demo_cases||[]){const option=document.createElement('option');option.value=item.id;option.textContent=item.label;caseSelect.appendChild(option)}caseSelect.addEventListener('change',showConsistencyCase);showConsistencyCase();$('consistency-button').addEventListener('click',runConsistencyDemo);$('submit-button').addEventListener('click',submit);$('reset-button').addEventListener('click',()=>{select.value='';reset()})}
init().catch(error=>{$('exercise-title').textContent='题目载入失败';$('requirement').textContent=error.message});
